api_hash: 00255a424638fee2b3e8afe309e77665
api_id: 9849275
chat_id: @onlyfansleaksvids
last_read_message_id: 0
ids_to_retry: []
media_types:
- audio
- document
- photo
- video
- voice
file_formats:
  audio:
  - all
  document:
  - pdf
  - epub
  video:
  - mp4
